newest version can run on rpi

diff --git a/ucore/uCore_test b/ucore/uCore_test
--- a/ucore/uCore_test
+++ b/ucore/uCore_test
@@ -3,12 +3,11 @@
 stdout=/dev/stdout
 stderr=/dev/stderr
 
-BUILD_DIR=${BUILD_DIR:-obj}
-RECORD_MODE=${RECORD_MODE:-}
+BUILD_DIR=obj
+RECORD_MODE=
 TEST_CASE=
 TIMEOUT=10
 WAIT_TIMEOUT=0
-MAX_PROCS=`grep processor /proc/cpuinfo | wc -l`
 
 DEFAULT_TEST=y
 UCORE_TEST_DIR=src/user-ucore
@@ -18,18 +17,15 @@ BIONIC_LIBC_TEST_ENABLED=
 : ${UCLIBC_TEST_DIR=../../ucore_lib_uclibc}
 UCLIBC_ENABLED=
 
+TEST_RESULT_DIR=
 BRK_FUNC=readline
 QEMU_SERIAL_LOG=serial.log
+TEST_SUITE_NAME=
 
-export SUMMARY=${SUMMARY:-$stdout}
+SUMMARY=$stdout
 TEST_LIST=testlist
-LOCK_FILENAME=.build-lock
 SPEC_TMP=.spec.tmp
 PATTERN_TMP=.pattern.tmp
-TOTAL_COUNT_TMP=.total.tmp
-PASSED_COUNT_TMP=.passed.tmp
-FAILED_COUNT_TMP=.failed.tmp
-BROKEN_COUNT_TMP=.broken.tmp
 
 SFSIMG_CLEAN=0
 
@@ -67,7 +63,7 @@ check_regexps() {
     reg=0
     error=
 
-    sed "/@.*$/d" $spec_file | sed "s/'/\n'/" | sed "s/^![ \t]*/!\n/" | sed "s/^-[ \t]*/-\n/" | sed "/^[[:space:]]*$/d" > $TEST_RESULT_DIR/$PATTERN_TMP.$$
+    sed "/@.*$/d" $spec_file | sed "s/'/\n'/" | sed "s/^![ \t]*/!\n/" | sed "s/^-[ \t]*/-\n/" | sed "/^[[:space:]]*$/d" > $TEST_RESULT_DIR/$PATTERN_TMP
     while read i; do
         if [ "x$i" = "x!" ]; then
             not=1
@@ -98,12 +94,18 @@ check_regexps() {
             not=0
             reg=0
         fi
-    done < $TEST_RESULT_DIR/$PATTERN_TMP.$$
+    done < $TEST_RESULT_DIR/$PATTERN_TMP
 
-    rm $TEST_RESULT_DIR/$PATTERN_TMP.$$
     if [ "$okay" = "yes" ]; then
+        printf "%10s\n" "[  PASS  ]" >> $SUMMARY
         return 0
     else
+        if [[ $HTML_OUTPUT = "y" ]]; then
+            printf "<font color=red><a href=\"%s\">%10s\n</a></font>" build-$UCONFIG_ARCH/$name.error "[  FAIL  ]" >> $SUMMARY
+        else
+            printf "%10s\n" "[  FAIL  ]" >> $SUMMARY
+        fi
+
         if [[ $RECORD_MODE != "y" ]]; then
             echo -e "$error" > $stderr
         else
@@ -114,37 +116,24 @@ check_regexps() {
     fi
 }
 
-# usage: print_info <test name> <result> <expected result> <count file>
-print_result() {
-    decorator='!'
-    if [ $2 = $3 ]; then
-        decorator=' '
-    fi
-    printf "%-60s[%c%6s%c]\n" "<$TEST_SUITE_NAME> $1" "$decorator" "$2" "$decorator" >> $SUMMARY
-    echo -n "$decorator" >> $4
-}
-
-# usage: acquire_lock <lock file path>
-acquire_lock() {
-    lockfile $1
-}
-
-# usage: release_lock <lock file path>
-release_lock() {
-    rm -r $1
-}
-
 # usage: run_test <testspec path>
 run_test() {
     TEST_SPEC=$1
-    name=`basename $TEST_SPEC .testspec`
-    source $BUILD_DIR/config/auto.conf
+
+    grep "^@sfs_force_rebuild[ \t]*$" $TEST_SPEC > /dev/null 2>&1
+    found=$(($? == 0))
+    if [ $found -eq 1 ] && [ $SFSIMG_CLEAN -ne 1 ]; then
+        rebuild_sfsimg
+        if [ $? -ne 0 ]; then
+            return 1
+        fi
+    fi
 
     arch=
     timeout=
     program=
-    grep "^@.*" $TEST_SPEC | sed "s/^@\([A-Za-z0-9_]*\)[ \t]*\(.*\)$/\1=\"\2\"/g" > $TEST_RESULT_DIR/$SPEC_TMP.$$
-    source $TEST_RESULT_DIR/$SPEC_TMP.$$
+    grep "^@.*" $TEST_SPEC | sed "s/^@\([A-Za-z0-9_]*\)[ \t]*\(.*\)$/\1=\"\2\"/g" > $TEST_RESULT_DIR/$SPEC_TMP
+    source $TEST_RESULT_DIR/$SPEC_TMP
     if [ -z $program ]; then
         return 10
     fi
@@ -154,74 +143,42 @@ run_test() {
             return 10
         fi
     fi
-    expected=" PASS "
-    if [ "$failin" ]; then
-        echo $failin | grep "\b$UCONFIG_ARCH\b" > /dev/null 2>&1
-        if [ $? -eq 0 ]; then
-            expected=" FAIL "
-        fi
-    fi
+    name=`basename $TEST_SPEC .testspec`
     if [ -z "$timeout" ] || [ $timeout -gt 600 ]; then
         timeout=$TIMEOUT
     fi
 
     export UCORE_TEST=$program
-    echo -n . >> $BUILD_DIR/$TOTAL_COUNT_TMP
-
-    acquire_lock $BUILD_DIR/$LOCK_FILENAME
-    grep "^@sfs_force_rebuild[ \t]*$" $TEST_SPEC > /dev/null 2>&1
-    found=$(($? == 0))
-    if [ $found -eq 1 ] && [ $SFSIMG_CLEAN -ne 1 ]; then
-        # FIXME: The arguments here are dummy
-        # It won't work if any test case other than those with uCore requires to rebuild the image
-        rebuild_testimg $UCORE_TEST_DIR sfs-orig.img
-        if [ $? -ne 0 ]; then
-            print_result $name "BROKEN" $expected $BUILD_DIR/$BROKEN_COUNT_TMP
-            return 1
-        fi
-        cp $BUILD_DIR/sfs.img $BUILD_DIR/sfs.img.$$
-    else
-        ln -s sfs.img $BUILD_DIR/sfs.img.$$
-    fi
+    printf "%-70s" "TEST <$TEST_SUITE_NAME> $name " >> $SUMMARY
 
     make O=$BUILD_DIR > /dev/null 2>&1
-    result=$?
-    cp $BUILD_DIR/kernel.img $BUILD_DIR/kernel.img.$$
-    cp $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf.$$
-    release_lock $BUILD_DIR/$LOCK_FILENAME
-    if [ $result -ne 0 ]; then
-        print_result $name "BROKEN" $expected $BUILD_DIR/$BROKEN_COUNT_TMP
+    if [ $? -ne 0 ]; then
+        printf "%10s\n" "[ BROKEN ]" >> $SUMMARY
         exit 1
     fi
 
     (
         ulimit -t $timeout
-    exec ./uCore_run -d $BUILD_DIR -t $$
+        exec ./uCore_run -d $BUILD_DIR -t
     ) > /dev/null 2>&1 &
     pid=$!
     sleep $WAIT_TIMEOUT
-    "$UCONFIG_CROSS_COMPILE"gdb -batch -nx \
-        -ex "target remote :$[ $$ % 10000 + 40000 ]" \
-        -ex "file $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf.$$"  \
+    "$UCONFIG_CROSS_COMPILE"gdb -batch -nx -x gdbinit.$UCONFIG_ARCH \
+        -ex "file $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf"  \
         -ex "b $BRK_FUNC" \
         -ex "c" > /dev/null 2>&1
 
     kill $pid > /dev/null 2>&1
     SFSIMG_CLEAN=0
 
-    check_regexps $BUILD_DIR/$QEMU_SERIAL_LOG.$$ $TEST_SPEC
-    case $? in
-        0)
-            print_result $name " PASS " $expected $BUILD_DIR/$PASSED_COUNT_TMP
-            ;;
-        1)
-            print_result $name " FAIL " $expected $BUILD_DIR/$FAILED_COUNT_TMP
-            ;;
-    esac
+    check_regexps $BUILD_DIR/$QEMU_SERIAL_LOG $TEST_SPEC
+    TEST_RESULT=$?
 
     if [[ $RECORD_MODE = "y" ]]; then
         tail -n 1 $SUMMARY
     fi
+
+    return $TEST_RESULT
 }
 
 # usage: run_test_suite <name> <src dir> <output file name>
@@ -229,7 +186,7 @@ run_test_suite() {
     if [ -z $3 ]; then
         return 1
     fi
-    export TEST_SUITE_NAME=$1
+    TEST_SUITE_NAME=$1
     rebuild_testimg $2 $BUILD_DIR/$3
     if [ $? -ne 0 ]; then
         return 1;
@@ -242,18 +199,29 @@ run_test_suite() {
         fi
         echo $TEST_CASE > $TEST_RESULT_DIR/$TEST_LIST
     else
-        find $2/testspecs -name *.testspec | while read file; do
-            timeout=`grep "^@timeout" $file | egrep -o "[0-9]+"`
-            echo ${timeout:-10} $file
-        done | sort -nr | grep -o " .*$" > $TEST_RESULT_DIR/$TEST_LIST
+        find $2/testspecs | grep "\.testspec$" | sort > $TEST_RESULT_DIR/$TEST_LIST
     fi
-    cat $TEST_RESULT_DIR/$TEST_LIST | xargs --max-procs=$MAX_PROCS -n 1 "$0" -1
+    while read spec; do
+        TOTAL=$(( ++TOTAL ))
+        run_test $spec
+        case $? in
+            0)
+                PASSED=$(( ++PASSED ))
+                ;;
+            1)
+                FAILED=$(( ++FAILED ))
+                ;;
+            10)
+                TOTAL=$(( --TOTAL ))
+                ;;
+        esac
+    done < $TEST_RESULT_DIR/$TEST_LIST
 }
 
-while getopts "d:f:hrs:t:w:1:" opt; do
+while getopts "d:f:hrs:t:w:" opt; do
     case $opt in
         d)
-            export BUILD_DIR=$OPTARG
+            BUILD_DIR=$OPTARG
             ;;
         f)
             TEST_CASE=$OPTARG
@@ -284,7 +252,7 @@ while getopts "d:f:hrs:t:w:1:" opt; do
             exit 0
             ;;
         r)
-            export RECORD_MODE=y
+            RECORD_MODE=y
             ;;
         s)
             DEFAULT_TEST=
@@ -312,17 +280,6 @@ while getopts "d:f:hrs:t:w:1:" opt; do
             ;;
         o)
             HTML_OUTPUT=y
-            ;;
-        1)
-            # This is a private option which should only be used in the script itself
-            run_test $OPTARG
-            result=$?
-            rm -f $BUILD_DIR/kernel.img.$$
-            rm -f $BUILD_DIR/sfs.img.$$
-            rm -f $BUILD_DIR/serial.log.$$
-            rm -f $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf.$$
-            exit $result
-            ;;
         ?)
             exit 1
             ;;
@@ -335,10 +292,10 @@ fi
 
 TIMESTAMP=`date +%Y%m%d-%H%M%S`
 if [[ $RECORD_MODE = "y" ]]; then
-    export TEST_RESULT_DIR=$BUILD_DIR/test-result.$TIMESTAMP
-    export SUMMARY=$TEST_RESULT_DIR/summary
+    TEST_RESULT_DIR=$BUILD_DIR/test-result.$TIMESTAMP
+    SUMMARY=$TEST_RESULT_DIR/summary
 else
-    export TEST_RESULT_DIR=/tmp/uCore_test
+    TEST_RESULT_DIR=/tmp/uCore_test
 fi
 mkdir -p $TEST_RESULT_DIR
 if [[ $RECORD_MODE = "y" ]]; then
@@ -347,10 +304,9 @@ fi
 
 source $BUILD_DIR/config/auto.conf
 
-touch $BUILD_DIR/$TOTAL_COUNT_TMP
-touch $BUILD_DIR/$PASSED_COUNT_TMP
-touch $BUILD_DIR/$FAILED_COUNT_TMP
-touch $BUILD_DIR/$BROKEN_COUNT_TMP
+TOTAL=0
+PASSED=0
+FAILED=0
 
 # uCore builtin test suite
 if [[ $UCORE_TEST_ENABLED = "y" ]] && [ -e $UCORE_TEST_DIR ]; then
@@ -367,24 +323,12 @@ if [[ $UCLIBC_TEST_ENABLED = "y" ]] && [ -e $UCLIBC_TEST_DIR ]; then
     run_test_suite "uclibc" $BIONIC_LIBC_TEST_DIR sfs-uclibc.img
 fi
 
-passed=`cat $BUILD_DIR/$PASSED_COUNT_TMP | wc -m`
-passed_unexpected=`grep -o '!' $BUILD_DIR/$PASSED_COUNT_TMP | wc -l`
-failed=`cat $BUILD_DIR/$FAILED_COUNT_TMP | wc -m`
-failed_unexpected=`grep -o '!' $BUILD_DIR/$FAILED_COUNT_TMP | wc -l`
-broken=`cat $BUILD_DIR/$BROKEN_COUNT_TMP | wc -m`
-total=`cat $BUILD_DIR/$TOTAL_COUNT_TMP | wc -m`
-
 echo "========== Test Summary ==========" >> $SUMMARY
-printf "%-8s%-20s%-20s%-10s%-10s\n" "" "passed(unexpected)" "failed(unexpected)" broken total >> $SUMMARY
-printf "%-8s%-20s%-20s%-10s%-10s\n" $UCONFIG_ARCH "$passed($passed_unexpected)" "$failed($failed_unexpected)" $broken $total >> $SUMMARY
-
-rm -f $BUILD_DIR/$TOTAL_COUNT_TMP $BUILD_DIR/$PASSED_COUNT_TMP $BUILD_DIR/$FAILED_COUNT_TMP $BUILD_DIR/$BROKEN_COUNT_TMP
-rm -f $BUILD_DIR/kernel.img.*
-rm -f $BUILD_DIR/sfs.img.*
-rm -f $BUILD_DIR/serial.log.*
-rm -f $BUILD_DIR/kernel/kernel-$UCONFIG_ARCH.elf.*
-rm -f $TEST_RESULT_DIR/$SPEC_TMP.*
+echo "  Total   $TOTAL" >> $SUMMARY
+echo "  Passed  $PASSED" >> $SUMMARY
+echo "  Failed  $FAILED" >> $SUMMARY
+echo "==================================" >> $SUMMARY
 
 if [[ $RECORD_MODE = "y" ]]; then
-    tail -n 3 $SUMMARY
+    tail -n 5 $SUMMARY
 fi
